### PR TITLE
Allow for easy build cache downloads

### PR DESCRIPTION
**Pull request by schneems**
```
$ heroku repo:download_cache -a issuetriage
heroku: linking plugin heroku-repo... done
Downloading... ████████████████████████▏  100% 00:00 72.23MB
```

```
$ ls | grep cache
issuetriage-cache.tgz
```

### CODE REVIEW

**Comment by schneems** [comment]
> Without product discussion, I would feel much more comfortable if we included this only in the sudo plugin, so it's only available to employees.

This has been useful for me for debugging a number of things. I don't feel this plugin in a generally available feature to customers, but is instead more of a power users tool. How about if we add a warning that it could go away at any time.

**Comment by edmorley** [comment]
I like the idea of adding this feature, and I think adding a warning it's experimental should be fine.

However if we do add it, please could we add it to https://github.com/heroku/heroku-builds instead? The cache-clearing part of heroku-repo is deprecated in favour of the heroku-builds plugin version (or was deprecated at least, before the reversal due to the cache metadata issue; we should return to that), and caches are more of a build implementation than a repo implementation detail. (I'm presuming it exists in this plugin only because caches used to live in the repo)

**Comment by schneems** [comment]
If we're deprecating the cache clearing from this repo, I think we should alias the command somehow. There is a lot of comments online suggesting people use this plugin and this command to clear cache.

Here's a very unscientific and incomplete set of anectdata https://stackoverflow.com/search?q=repo%3Apurge_cache

**Comment by schneems** [comment]
I'm reviving this thread. I think that it's still valuable for debugging (as i'm using it right not on 997022. FWIW you can use this feature before it's merged:

```
git clone https://github.com/heroku/heroku-repo
cd heroku-repo
git fetch
git checkout schneems/download-cache
heroku plugin:link ./
```

I've added an "experimental" tag and warning to the command per @edmorley's suggestion.

**Comment by edmorley** [comment]
Hi! Thank you for working on this - agree this would be very useful for debugging! :-)

However I think we should add this to https://github.com/heroku/heroku-builds instead, since this plugin is somewhat legacy (it exists from the era when the repo and cache were stored together). And having cache related functionality in the "builds" plugin makes more sense from a discoverability point of view.

(Separately we should figure out the difference in cache purging; but that's orthogonal)

**Comment by schneems** [comment]
Thanks, @edmorley I wasn't sure that change was still desired since this code continues to work and the previously discussed work to move cache purging functionality to the builds plugin doesn't seem to have happened. 

Also aren't you supposed to be OOO today 🙈

**Pull request closed without merging**
